version: '1.0'

services:
  postgres:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - pnpm-monorepo-boilerplate-db-data:/var/lib/postgresql/data
    ports:
      - 6543:5432

volumes:
  pnpm-monorepo-boilerplate-db-data:
    name: pnpm-monorepo-boilerplate-db-data
