#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm lint-staged

check_if_history_file_updated() {
  BRANCH=$(git rev-parse --abbrev-ref HEAD);
  if [ $BRANCH = "main" ]; then
    echo "[CHECKIT] Maybe history file not updated!";
    # dont know why --cached --quiet not working so I decide to use history
    # TODO: find another way
    git diff --cached --name-only | grep '^history.md$';
  fi
  exit 0;
}

check_if_history_file_updated;